### ISSUE TITLE
Recomendação: módulo systemd no Ansible

### ISSUE THREAD

**Issue by glaucoleme** [glaubergf/Ansible#1]
Olá, Glauber! Vi [seu post](https://sempreupdate.com.br/como-instalar-e-configurar-o-zabbix-5-no-debian-10-com-ansible/) sobre como instalar e configurar o Zabbix utilizando o Ansible.

Achei bem interessante, principalmente porque nas últimas semanas passei pelo mesmo esforço, instalando em servidores Ubuntu. Não tenho muita coisa a acrescentar, pois o artigo está bem completo. Parabéns!

Gostaria de te dar a dica de alterar o uso de comandos systemd pelo próprio [modulo do ansible](https://docs.ansible.com/ansible/latest/modules/systemd_module.html) pra esse tipo de tarefa.

Um exemplo seria alterar o código de:

```YAML
# Código da tarefa de instalação do Zabbix - Linha 202
# https://github.com/glaubergf/Ansible/blob/c902abb8be756a160040818d2b3f3569bf103a3e/ProjZabbix/task/install_zabbix_v5.yml#L202
  - name: Reiniciando o Zabbix Server, Zabbix Agente e PHP
    command: "{{ item }}"
    with_items:
      - systemctl enable zabbix-server zabbix-agent nginx
      - systemctl restart zabbix-server zabbix-agent nginx php7.3-fpm
    tags: zbx
```

para algo do tipo: 

```YAML
  - name: Reiniciando o Zabbix Server, Zabbix Agente e PHP
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: restarted
      daemon_reload: yes
    with_items:
      - 'zabbix-server'
      - 'zabbix-agent'
      - 'nginx'
      - 'php7.3-fpm'
    tags: zbx
```

A vantagem do uso dos módulos é a garantida da RedHat de manter os módulos compatíveis mesmo com mudanças futuras.
